global:
  scrape_interval:     15s 

  
  external_labels:
    monitor: 'codelab-monitor'


scrape_configs:
  
  - job_name: 'prometheus'
    metrics_path: /metrics
    
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'csvserver'
    metrics_path: /metrics
    
    scrape_interval: 5m

    static_configs:
      - targets: ['csvserver:9300']